---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: polinavngrd/nginx:~v4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/polinavinograd/nginx-app.git
    targetRevision: master
    path: .
    helm:
      parameters:
#        - name: "replicaCount"
#          value: "1"
        - name: "image.repository"
          value: polinavngrd/nginx
        - name: "image.tag"
          value: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true


