image:
  repository: polinavngrd/nginx
  pullPolicy: IfNotPresent
  tag: ""

volumeMounts:
  - name: nginx-config-volume
    mountPath: /etc/nginx/conf.d
  - name: nginx-start-page-volume
    mountPath: /var/www/html/index.html
    subPath: index.html

volumes:
  - name: nginx-config-volume
    secret:
      secretName: nginx-config
  - name: nginx-start-page-volume
    configMap:
      name: nginx-start-page

