apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    app: apache
spec:
  type: {{ .Values.apache_service.type }}
  ports:
    - port: {{ .Values.apache_service.port }}
      targetPort: {{ .Values.apache_service.targetPort }}
      protocol: TCP
  selector:
    app: apache
