apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  labels:
    app: apache
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.apache_replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: polinavngrd/apache:v-20240209-131500
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.apache_service.port }}
