apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  labels:
    app: apache
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.apache_replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: "{{ .Values.apache_image.repository }}:{{ .Values.apache_image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apache_image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apache_service.port }}
          resources:
            {{- toYaml .Values.apache_resources | nindent 12 }}
