apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: polinavngrd/apache:v-20240209-131500
          ports:
            - containerPort: 8080
