apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.nginx_replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: "{{ .Values.nginx_image.repository }}:{{ .Values.nginx_image.tag }}"
          imagePullPolicy: {{ .Values.nginx_image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx_service.port }}
          resources:
            {{- toYaml .Values.nginx_resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
