apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: {{ .Values.nginx_service.type }}
  ports:
    - port: {{ .Values.nginx_service.port }}
      targetPort: {{ .Values.nginx_service.targetPort }}
      protocol: TCP
      nodePort: 30080
  selector:
    app: nginx
